project_id = "bqbuzostprysntoibpbp"

[functions.notify-admin-new-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.schedule-notifications]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false
